### ISSUE TITLE
错误字符串

### ISSUE THREAD

**Issue by ZhuJD-China** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#10]
_className  未声明定义

**Comment by UNeedCryDear** [comment]
哪行哪句报的错误，这个参数定义在头文件里面，你用的onnx还是opencv的，找到对应头文件搜索一下就知道在哪里了。

**Comment by Auguuu** [comment]
错误	C2039 "_className": 不是 "YoloSeg" 的成员 main.cpp 37	
这个_className 一直报错

**Comment by UNeedCryDear** [comment]
> 错误 C2039 "_className": 不是 "YoloSeg" 的成员 main.cpp 37 这个_className 一直报错

检查一下头文件里面的这个_className ，你是不是改成了private了，不行的话这个前面价格public就可以了，外部无法直接访问私有成员变量的。或者你可以直接定义一个class name的vector数组，将test._className换成你自己的，这个是绘制结果的时候需要加上类名，对于推理不影响。

**Comment by Auguuu** [comment]
> 



> > 错误 C2039 "_className": 不是 "YoloSeg" 的成员 main.cpp 37 这个_className 一直报错
> 
> 检查一下头文件里面的这个_className ，你是不是改成了private了，不行的话这个前面价格public就可以了，外部无法直接访问私有成员变量的。或者你可以直接定义一个class name的vector数组，将test._className换成你自己的，这个是绘制结果的时候需要加上类名，对于推理不影响。

感谢您的回复，这个问题解决了，把报错的位置附近的注释删除掉就好了。
