### ISSUE TITLE
请问onnxruntime安装是GPU版本的吗？【目前，我使用onnxruntime-cpu 1.12.0可以解决问题了】

### ISSUE THREAD

**Issue by liuqinglong110** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#11]
编译过程中提示了一些报错。我确定自己安装的onnxruntime(cpu版)是安装成功的。因为我先用Yolov5的V6.1版本调用Onnxruntime成功运行了。

但是我在编译过程中出现报错，报错内容如下：无法解析的外部符号 OrtSessionOptionsAppendExecutionProvider_CUDA

**Comment by UNeedCryDear** [comment]
这个是cuda的api，如果你不用cuda的话，可以注释掉xuda相关的设置即可

**Comment by UNeedCryDear** [comment]
另外，我看你的报错截图，你onnxruntime应该是1.12以前的版本对吗，这个等会我修改一下，目前的版本应该是适用于onnxruntime1.12以后的版本，以前的版本API变动了。

**Comment by liuqinglong110** [comment]
> 这个是cuda的api，如果你不用cuda的话，可以注释掉xuda相关的设置即可
嗯嗯，感谢！我找到位置了，注释了红色方框的代码就可以了，问题已经解决了。正在学习中，再次感谢！

![11](https://user-images.githubusercontent.com/23652342/221111221-55ba9298-6f30-4b62-b005-da8544a7fb21.png)

**Comment by liuqinglong110** [comment]
> 另外，我看你的报错截图，你onnxruntime应该是1.12以前的版本对吗，这个等会我修改一下，目前的版本应该是适用于onnxruntime1.12以后的版本，以前的版本API变动了。

是的。我最开始发了一张报错很多的图片，当时用的是onnxruntime  1.3.0的版本。后来换成1.12.0的就没什么问题了。

**Comment by UNeedCryDear** [comment]
我加了旧版本的API支持，但是我不确定你的1.3.0能否运行，我只测试到了1.9.0的版本，再之前的我没测试了。如果你更新代码之后可以在1.3.0下面运行的话，可以告诉我下，我更改下版本需求

**Comment by liuqinglong110** [comment]
> 我测试了一下onnxruntime1.3.0（CPU）版本，不行。应该是有些函数缺少。
![12](https://user-images.githubusercontent.com/23652342/222881604-139bfc69-7f75-4255-a6b1-5ea634adbc00.png)

**Comment by liuqinglong110** [comment]
另外，我把onnxruntime1.12.0 、1.13.1、1.14.0（均为CPU版）都实验了一下。在windows10、visual studio2017环境上，所有的release  x64都是编译成功并且也运行成功的。但是所有版本的debug x64都会报错。
报错如下：
![13](https://user-images.githubusercontent.com/23652342/222884921-d256c2f8-3346-4c03-8932-f3311162294a.png)
通过定位具体找到了报错的那行代码：
![14](https://user-images.githubusercontent.com/23652342/222884935-ab2bb44c-cacb-47c3-a1a8-87105735e18f.png)
然后通过搜索，发现其他人大致遇到类似情况，当然我不知道对方是不是在debug运行过程中报错：
![image](https://user-images.githubusercontent.com/23652342/222884984-2b9ef240-fc8b-417c-a656-f2689a7c3fc8.png)
图片来源：https://www.eet-china.com/mp/a116771.html
目前还没有解决debug编译正确，但是运行报错的问题。

**Comment by UNeedCryDear** [comment]
将dll拷贝到项目的exe下面，debug就有这个毛病，配置环境路径不行

**Comment by UNeedCryDear** [comment]
还有一种就是你编译的版本和你实际读取到的dll版本不一样也是会出现这个问题
