### ISSUE TITLE
预训练模型加载正常，但自训练模型报错

### ISSUE THREAD

**Issue by 690696306** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#13]
你好，我使用yolov5s-seg.pt 预训练模型进行测试时，一切正常，但用这个模型训练自己的数据集后，用onnx则会在yolov5_seg_utils.cpp 中的mask 部分就会报错。用opencv 会在yolo_seg.cpp 的float box_score = pdata[4]这里报错。

![image](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/133076485/ec2addc0-cadf-4371-ad13-6351743ced68)

![image](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/133076485/26225167-d41d-4cd9-9e7c-baa6feaaae92)

训练时也尝试了不同的环境，都是一样的结果
训练环境1：
python:3.10.9
pytorch 1.12
cuda 11.6

训练环境2：
python:3.10.9
pytorch 1.10
cuda 11.3

c++ 推理环境：
opencv 4.6.0
onnx 1.9.0 cpu

**Comment by UNeedCryDear** [comment]
自己的模型要修改类别名字，类别数据不对越界了。
但是我比较奇怪的是，上面的assert不会报错吗？   
https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/blob/3f477d154672c08f88f7852a6b3c694a891dc587/yolo_seg.cpp#L67

**Comment by UNeedCryDear** [comment]
opencv的话你需要将这里面的参数设置改对，改成你导出的时候用imgs大小，然后segW和segH为你训练的时候imgs除以mask缩放系数。onnx那边同理
https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/blob/3f477d154672c08f88f7852a6b3c694a891dc587/yolo_seg.h#L23
如果还是不行的话，你可以提供一下模型，我可以帮你看下要改哪些位置的参数，还是参数正确，代码出现了bug
