### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by Fightyyyy** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#14]
怎么在vs上面使用呀？

**Comment by UNeedCryDear** [comment]
新建win32 控制台应用程序，附加选项里面勾上空项目，点击完成。
接着配置好相应的opencv环境，如果要用onnxruntime也要配置对应的环境，这个如果不会配置度娘搜索下就有。
然后下载源码，修改源码换行符（LF ->CR LF），将以下部分拷到项目路径下面去
![image](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/52729998/30a11b63-2a71-4d8a-9f25-8aeadfa8ccdc)

在vs项目资源管理器中源文件右键->添加->现有项,找到下面几个h和cpp文件添加进去。最后修改模型路径和图片路径就行
![image](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/52729998/53d34a2a-36c5-4d40-b1e6-63069df75671)

**Comment by TopkingTs** [comment]
请问在release过程中怎么会出现这么多如图所示的错误，在网上搜了好久都找不到解决办法，所以只好来问您一下 麻烦了


我是小白 懂得不多 请勿见怪
![EZ5O 8PGB X6Q5N%V5HMPFW](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/140034618/f79138bb-98ee-47aa-ba31-e1977da21957)

**Comment by TopkingTs** [comment]
感谢您的回答 我按照上面您说的重新配了一下竟然神奇的可行了 再次感谢

**Comment by TopkingTs** [comment]
还有个问题 请问这样是什么情况？
![)I_6J~`}7 ZI3XJE8)V7HS](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/140034618/e34f9627-977b-492d-b547-c44bbbb441ed)

**Comment by UNeedCryDear** [comment]
把onnxruntime的dll拷贝到exe路径下面，由于win10系统在system32下面有一个同名的onnxruntime.dll，而且优先级比较高，所以会默认使用这个dll导致这个错误。如果你会删除system32下面的dll的话就不需要拷贝，不会的话就按开头说的就行

**Comment by TopkingTs** [comment]
![HVH0BS0()~234}$XNZ)X~H4](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/140034618/170361ab-85a5-4bd6-8b39-054e896f60fd)
请问这种情况该怎么解决呢TOT

**Comment by UNeedCryDear** [comment]
https://netron.app
用这个打开你的onnx文件，看下你的输入和输出是什么，你是不是用错文件了，还是哪里设置错误了

**Comment by TopkingTs** [comment]
感谢您 我再排查一下 谢谢您的帮助
