### ISSUE TITLE
请问这种情况是哪地方错误了？

### ISSUE THREAD

**Issue by Fightyyyy** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#15]
第二句warning哪里怎么配置GPU？
第三局detect failed 是哪里出现问题？
![8(SH(UE0)8@Z%~2(6D M5%X](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/140034618/7e3fbe17-eb84-453c-b93e-24e1c196fc23)

**Comment by Fightyyyy** [comment]
还有这里的几个参数  图片输入高度和宽度我理解 后面seg_width seg_height seg_channels是什么参数呀？
![(524W7M5@L{B50}KBJI9TUP](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/140034618/10ad41ae-c200-4805-8b39-ebf155910ffa)

**Comment by UNeedCryDear** [comment]
1. 你用opencv来推理的话，调用GPU需要编译opencv。如果是onnxruntime的话就不需要，下载好onnxruntime，配置好cuda之类的就可以了。
2. 跟你说了用netron.app开下你的onnx文件，看下你的输入输出就知道这个参数什么意思了，输入是一个图片，输出有两个，这个对应的就是其中的protos的输出参数。并且我注释都给你写了是netWidth/mask_ratio,你训练的时候没注意到train下面有个默认的mask_ratio为4的参数吗？目前这个参数默认导出的onnx都是4，不用改。

**Comment by Fightyyyy** [comment]
感谢你的回答，看到了默认是4了 当时没注意 抱歉。可是为什么会detect failed呢？没用onnxruntime

**Comment by UNeedCryDear** [comment]
1. 你用opencv来推理的话，调用GPU需要编译opencv。如果是onnxruntime的话就不需要，下载好onnxruntime，配置好cuda之类的就可以了。
2. 跟你说了用netron.app开下你的onnx文件，看下你的输入输出就知道这个参数什么意思了，输入是一个图片，输出有两个，这个对应的就是其中的protos的输出参数。并且我注释都给你写了是netWidth/mask_ratio,你训练的时候没注意到train下面有个默认的mask_ratio为4的参数吗？目前这个参数默认导出的onnx都是4，不用改。

**Comment by UNeedCryDear** [comment]
没有检测到结果啊，你稍微看下代码？这if else的逻辑又不是什么难上天的

**Comment by Fightyyyy** [comment]
好的 谢谢
