### ISSUE TITLE
为什么运行不出现结果

### ISSUE THREAD

**Issue by LFL19991003** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#16]
![image](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/assets/100058617/27f007c0-91f5-4d37-8a7f-cf9e636b63a5)
没有结果显示就结束了，请问是什么原因呢

**Comment by UNeedCryDear** [comment]
不是很清楚，是图片没有读取到还是你的cv::imshow()函数缺少东西show失败了？
你需要打个断点看下是哪里直接return了。
