### ISSUE TITLE
onnxruntime推理出错

### ISSUE THREAD

**Issue by LYHTZHANGJIANG** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#18]
2023-10-17 09:47:02.711437464 [E:onnxruntime:Yolov5-Seg, allocatormgr.cc:44 CreateAllocator] Received invalid value of arena_extend_strategy 12684664
Segmentation fault (core dumped）

**Comment by UNeedCryDear** [comment]
确认下断点的位置，你目前给出的报错我无法看出来是什么问题。

**Comment by linglongxian** [comment]
@LYHTZHANGJIANG 你好，请问你解决这个问题了吗？我也遇到这个问题了

**Comment by linglongxian** [comment]
@LYHTZHANGJIANG @UNeedCryDear 
我是用的作者的《yolov8-opencv-onnxruntime-cpp》遇到的这个类似问题，然后在cudaOption那里增加了两个语句就可以正常运行了
OrtCUDAProviderOptions cudaOption;
cudaOption.device_id = cudaID;
 cudaOption.arena_extend_strategy = 1;
cudaOption.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::HEURISTIC;
