### ISSUE TITLE
如何在ubuntu下运行？

### ISSUE THREAD

**Issue by HXB-1997** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#21]
需要安装visual studio吗

**Comment by UNeedCryDear** [comment]
？
linux你安装vs干嘛，vs是win下面的。
linux下面运行最简单的就是用cmake的方式编译，你可以按照这个改一下就是v5的
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/main/CMakeLists.txt

**Comment by HXB-1997** [comment]
> ？ linux你安装vs干嘛，vs是win下面的。 linux下面运行最简单的就是用cmake的方式编译，你可以按照这个改一下就是v5的 https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp/blob/main/CMakeLists.txt

感谢，我试试
