### ISSUE TITLE
undefined reference to `OrtSessionOptionsAppendExecutionProvider_CUDA'

### ISSUE THREAD

**Issue by HXB-1997** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#22]
Ubuntu 20.04运行make指令报错：
[100%] Linking CXX executable YOLOv5
/usr/bin/ld: CMakeFiles/YOLOv5.dir/yolov5_seg_onnx.cpp.o: in function `YoloSegOnnx::ReadModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool)':
yolov5_seg_onnx.cpp:(.text+0x219): undefined reference to `OrtSessionOptionsAppendExecutionProvider_CUDA'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/YOLOv5.dir/build.make:325: YOLOv5] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/YOLOv5.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
我将#define ORT_OLD_VISON 12改为#define ORT_OLD_VISON 13后还是报这个错误

**Comment by UNeedCryDear** [comment]
你安装的onnxruntime不是GPU的版本，就会报这个错误，也就是找不到OrtSessionOptionsAppendExecutionProvider_CUDA这个选项，这个跟ORT的版本大小关系不大的，如果你确认是CPU的版本，可以将这句注释掉就可以正常使用了。
