### ISSUE TITLE
Detect failed!

### ISSUE THREAD

**Issue by LeungWaiHo** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#23]
我在yolov5里训练了一个分割模型，类别只有“box“一类，导出为onnx的时候，（className已改为只有”box“一类）输出的boxScore都是很小的值，导致无输出boxes，但是训练出来（被导出）的模型我在yolov5里面是正常运行的

**Comment by UNeedCryDear** [comment]
你看下导出的onnx参数是什么，是不是按照我readme中导出的方式来导出的。
另外，我这里的yolov5的版本默认是6.0及其以后的版本，如果你是6.0之前的，估计也会有点问题。
