### ISSUE TITLE
在代码中有一个_strideSize的参数

### ISSUE THREAD

**Issue by weiqwert** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#7]
在代码中有_strideSize的这个参数，想知道这个参数的大小是根据什么来定的，还是说这个_strideSize为固定的size=3？我在更换了我自己训练的数据集以后，改了 _netWidth 、_netHeight 、_segWidth = 160;    _segHeight 后会报错。

**Comment by UNeedCryDear** [comment]
stride size是用来控制你你的检测头有多少个输出口的，像P5模型有三个输出口（类似yolov5n/s/m/x/l-seg.pt），分别是8,16,32步长，那么stride就是3,而有些检测用的是P6模型，类似yolov5n6/s6/x6/l6-seg.pt等等，这种的步长是8,16,32,64，stide size就是4.
至于设置，看你用的预训练模型或者model.yaml里面的设置是哪种类型。你如果不知道的话，可以用https://netron.app/ 打开你的onnx模型，看下你的输入输出显示的是多少的。

另外，修改成自己的模型，你还要换class names，这个参数要换成你自己的类别名，至少长度要对的上才行，不然就是越界段错误，或者检测结果不对。
