### ISSUE TITLE
代码崩溃：

### ISSUE THREAD

**Issue by xinsuinizhuan** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#8]
![图片](https://user-images.githubusercontent.com/40679769/211733791-834ebd0d-43bc-45fb-bb07-7ca0c456a99f.png)
这个位置，有的图像，也会引起崩溃，超限问题，怎么来判定避免？
![图片](https://user-images.githubusercontent.com/40679769/211734039-47896244-4b6c-4fe5-b728-dbc55163698b.png)
![图片](https://user-images.githubusercontent.com/40679769/211734102-77b1106f-3846-4562-952b-85083dd9dc4c.png)

8+65=73，超了72，所以崩溃

**Comment by UNeedCryDear** [comment]
加个防呆，像你这个如果超过的72的话，就用72.这部分等会我更新下看看，你可以自己加上去。

**Comment by xinsuinizhuan** [comment]
还会有崩溃：
![图片](https://user-images.githubusercontent.com/40679769/211743292-75df076b-3835-4594-bfdf-7a9bfcad58ce.png)
mask是64*102
![图片](https://user-images.githubusercontent.com/40679769/211743372-8e33cb35-d995-480d-aa28-d54cf2d4dbe2.png)
但是box确是65*102
[football1.zip](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/files/10389726/football1.zip)
您测试一下下面这个附件视频

**Comment by xinsuinizhuan** [comment]
我就是跑这个视频时，崩溃的，图片不崩溃，不好抓崩溃的图

**Comment by xinsuinizhuan** [comment]
跟模型没关系，就是有些超限判断，n模型和s模型，都会崩溃

**Comment by UNeedCryDear** [comment]
引擎是onnxruntime还是opencv

**Comment by xinsuinizhuan** [comment]
onnxruntime和opencv两个都会崩溃

**Comment by UNeedCryDear** [comment]
我已经回滚了，一共243帧，我这里并不会崩掉
![image](https://user-images.githubusercontent.com/52729998/211748794-e5ffd62e-391c-43d0-a657-5ae18890e0c4.png)

**Comment by UNeedCryDear** [comment]
你更新下除了main.cpp外的文件看下还会不会

**Comment by xinsuinizhuan** [comment]
奇怪了。我重新更新下，跑一下。

**Comment by xinsuinizhuan** [comment]
> 你更新下除了main.cpp外的文件看下还会不会

这个地方，是一个很玄虚的地方
cv::Vec4f params = mask_params.params;
这个变量名称是只有params不会报错，也不会崩溃
![图片](https://user-images.githubusercontent.com/40679769/211822852-90d8ce64-ea5b-4cef-9f4e-1d9bb91361d7.png)

但是，当我便更一个名称，则l立马崩溃：
![图片](https://user-images.githubusercontent.com/40679769/211823089-37c41348-ed0b-4e9d-86d0-0b00b7f4d9eb.png)

**Comment by UNeedCryDear** [comment]
变量名修改不是问题，应该是哪里修改没改完整，导致某一帧的参数不一致，但是你这里的参数没有修改过来导致的。我这里的零时变量又不是什么智能指针啥的，像unique_ptr这个坑，使用一次就失效了。

**Comment by xinsuinizhuan** [comment]
那个变量问题，确实是我下面没改过来导致的，但是另外一个诡异的问题是，我吧Getmask2里面的内容，复制出来替换了Getmask2，在这个里面，我使用直接使用params，而不是mask_params中的params，就会崩溃：

for (int i = 0; i < temp_mask_proposals.size(); ++i) {
		//GetMask2(cv::Mat(temp_mask_proposals[i]).t(), net_output_img[1], output[i], mask_params);
		cv::Mat maskProposals = Mat(temp_mask_proposals[i]).t();
		cv::Mat maskProtos = net_output_img[1];
		int seg_channels = mask_params.segChannels;
		int net_width = mask_params.netWidth;
		int seg_width = mask_params.segWidth;
		int net_height = mask_params.netHeight;
		int seg_height = mask_params.segHeight;
		float mask_threshold = mask_params.maskThreshold;
		cv::Vec4f maskparams = mask_params.params;
		cv::Size src_img_shape = mask_params.srcImgShape;

		cv::Rect temp_rect = output[i].box;
		//crop from mask_protos
		//int rang_x = floor((temp_rect.x * maskparams[0] + maskparams[2]) / net_width * seg_width);
		//int rang_y = floor((temp_rect.y * maskparams[1] + maskparams[3]) / net_height * seg_height);
		//int rang_w = ceil(((temp_rect.x + temp_rect.width) * maskparams[0] + maskparams[2]) / net_width * seg_width) - rang_x;
		//int rang_h = ceil(((temp_rect.y + temp_rect.height) * maskparams[1] + maskparams[3]) / net_height * seg_height) - rang_y;

		int rang_x = floor((temp_rect.x * params[0] + params[2]) / net_width * seg_width);
		int rang_y = floor((temp_rect.y * params[1] + params[3]) / net_height * seg_height);
		int rang_w = ceil(((temp_rect.x + temp_rect.width) * params[0] + params[2]) / net_width * seg_width) - rang_x;
		int rang_h = ceil(((temp_rect.y + temp_rect.height) * params[1] + params[3]) / net_height * seg_height) - rang_y;

		//int rang_x = floor((temp_rect.x * params[0] + params[2]) / _netWidth * _segWidth);
		//int rang_y = floor((temp_rect.y * params[1] + params[3]) / _netHeight * _segHeight);
		//int rang_w = ceil(((temp_rect.x + temp_rect.width) * params[0] + params[2]) / _netWidth * _segWidth) - rang_x;
		//int rang_h = ceil(((temp_rect.y + temp_rect.height) * params[1] + params[3]) / _netHeight * _segHeight) - rang_y;

		rang_w = MAX(rang_w, 1);
		rang_h = MAX(rang_h, 1);
		if (rang_x + rang_w > seg_width) {
			if (seg_width - rang_x > 0)
				rang_w = seg_width - rang_x;
			else
				rang_x -= 1;
		}
		if (rang_y + rang_h > seg_height) {
			if (seg_height - rang_y > 0)
				rang_h = seg_height - rang_y;
			else
				rang_y -= 1;
		}

		vector<cv::Range> roi_rangs;
		roi_rangs.push_back(cv::Range(0, 1));
		roi_rangs.push_back(cv::Range::all());
		roi_rangs.push_back(cv::Range(rang_y, rang_h + rang_y));
		roi_rangs.push_back(cv::Range(rang_x, rang_w + rang_x));

		//crop
		cv::Mat temp_mask_protos = maskProtos(roi_rangs).clone();
		cv::Mat protos = temp_mask_protos.reshape(0, { seg_channels,rang_w * rang_h });
		cv::Mat matmul_res = (maskProposals * protos).t();
		cv::Mat masks_feature = matmul_res.reshape(1, { rang_h,rang_w });
		cv::Mat dest, mask;

		//sigmoid
		cv::exp(-masks_feature, dest);
		dest = 1.0 / (1.0 + dest);

		int left = floor((net_width / seg_width * rang_x - params[2]) / params[0]);
		int top = floor((net_height / seg_height * rang_y - params[3]) / params[1]);
		int width = ceil(net_width / seg_width * rang_w / params[0]);
		int height = ceil(net_height / seg_height * rang_h / params[1]);

		resize(dest, mask, cv::Size(width, height), INTER_NEAREST);
		mask = mask(temp_rect - cv::Point(left, top)) > mask_threshold;
		output[i].boxMask = mask;
	}

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/211949019-5d6692a6-35f4-4b1c-b843-733167bb63ea.png)

**Comment by UNeedCryDear** [comment]
这种情况只能debug一下看看你这个变了量从哪里开始变得和params不一致，是什么原因导致的。

**Comment by xinsuinizhuan** [comment]
我debug看了，一样的。就是很神奇。
